### ISSUE TITLE
Installation: problem with dependency to SnakeYAML 1.18

### ISSUE THREAD

**Issue by tfesenko** [Nasdanika/docgen-ecore#1]
I tried installing Nasdanika DocGen Ecore from http://www.nasdanika.org/products/docgen-ecore/repository (https://marketplace.eclipse.org/content/nasdanika-ecore-documentation-generator#group-details does not work, should I created another issue for it?). It fails with the following error because the plugin has a dependency to `org.yaml.snakeyaml 1.18.0`, but it's not shipped with the update site:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Ecore Documentation Generator Feature 1.0.0.201802052014 (org.nasdanika.docgen.ecore.feature.feature.group 1.0.0.201802052014)
  Missing requirement: Ecore 1.0.0.201802052014 (org.nasdanika.docgen.ecore 1.0.0.201802052014) requires 'bundle org.yaml.snakeyaml 1.18.0' but it could not be found
  Cannot satisfy dependency:
    From: Ecore Documentation Generator Feature 1.0.0.201802052014 (org.nasdanika.docgen.ecore.feature.feature.group 1.0.0.201802052014)
    To: org.nasdanika.docgen.ecore [1.0.0.201802052014]
```

## Attempt 2: With SnakeYAML from Orbit: Failed
So, I went ahead and installed SnakeYAML 1.14 from http://download.eclipse.org/tools/orbit/downloads/drops/R20180206163158/ . Note that Orbit provides version 1.14, while DocGen Ecore requires the version 1.18. As expected, it installing SnakeYAML 1.4 and restarting Eclipse did not help with my second attempt to install DocGen. It fails with a similar message.

## Solution
Orbit provides tycho-friendly versions of some popular java libraries. Usually, it's a good practice to use exactly the same version as provided  by Orbit. As there any reason of not using SnakeYAML 1.14 and using SnakeYAML 1.18 instead? 
It would also be good to provide all required dependencies including SnakeYAML as a part of the update site to make installation easy.

**Comment by pvlasov** [comment]
The repository now contains all dependencies including Snake YAML 1.18. Please give it another try.

**Comment by tfesenko** [comment]
Thanks, @pvlasov ! It works now, I successfully installed  `v1.0.0.201803021841`
